name: Build

on:
  push:
    branches: main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
          repository: macrat/squid
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: macrat/squid:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
