name: Build

on:
  push:
    branches: main
  schedule:
    - cron: '25 0 1 * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: login
        uses: docker/login-action@v1
        with:
          username: macrat
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: generate tags
        id: tags
        run: 'echo "::set-output name=TAGS::macrat/squid:latest,macrat/squid:$(date +%Y-%m-%d)"'
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.tags.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
