name: Build

on:
  push:
    branches: main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: login DockerHub
        uses: docker/login-action@v1
        with:
          username: macrat
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: login GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: macrat
          password: ${{ secrets.GHCR_TOKEN }}
      - name: generate tags
        id: tags
        run: |
          TAGS="macrat/squid:latest"
          TAGS="${TAGS},macrat/squid:$(date +%Y-%m-%d)"
          TAGS="${TAGS},ghcr.io/macrat/squid:latest"
          TAGS="${TAGS},ghcr.io/macrat/squid:$(date +%Y-%m-%d)"
          echo "::set-output name=TAGS::${TAGS}"
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.tags.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
